// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<String> greet({required String name}) =>
    RustLib.instance.api.crateApiGreet(name: name);

Future<String> getTosStatus() => RustLib.instance.api.crateApiGetTosStatus();

Future<TosState> getInitialState() =>
    RustLib.instance.api.crateApiGetInitialState();

Future<void> setHierarchyLevel({required TosState state, required int level}) =>
    RustLib.instance.api.crateApiSetHierarchyLevel(state: state, level: level);

Future<List<String>> getSystemLogs({required TosState state}) =>
    RustLib.instance.api.crateApiGetSystemLogs(state: state);

Future<void> addLogEntry({required TosState state, required String text}) =>
    RustLib.instance.api.crateApiAddLogEntry(state: state, text: text);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<TosState>>
abstract class TosState implements RustOpaqueInterface {}
